keys:
  - &pgp_key 217877836071F0A75B262A69F328F0A0914407EF!
  - &age_key age1tvkzsh9g7gzlau3c2kcnrjwdgara020ekz685twd3sxy0qheuarqgj49w2
  - &duskglow_machine_key age1ykpdxjvemt4yzgalzmrgfdznpk6hmt4p06gzg7cdz0ac09n3qpkqgs4x04
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *age_key
          - *duskglow_machine_key
        pgp:
          - *pgp_key
